language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
services:
- postgresql
script:
- "./manage.py test"
deploy:
  provider: heroku
  api_key:
    secure: izNW4bFNLPrKkW7HxEsEg2jnZrp9DYGD3z45MLVSHx1S0ZtizOm+60m9JZaIt6aASL+kQzcKSnNe92X/wnlff4mkQByqcKrSrQsiitm/Q4k81Jj09iUBGoEZJ8vgCq3d2lwt5goRHxcU7ukTbK5zr0G5wgwJ0R8vPjmuxsEWa/bJQyztkcfLb/41kjDGni7BDWAjB3wU3uadXZQkf1il555GjYC5ZR7VgtTRUfFTkU2axemxV2nYlq+hTFG9Q7D4/5LewzzwqO10oyIlxUIiw1CxDmQXi24EfW7zujV45W9nyj+4wKxs3O9a8qjfLDtrUYoJQ+ec5J6Oms0xtDEFNo8eYfF4sby+brJh5wTa/qvyUJJBgc4KnRPw5RYdGdtaxSOcohpn14UAgYmjoQNhf9QrYxLXBM0o0tMnx/8mSGyrQVTN2X/eprL5ZedfBWk8mp4Onw1DJgph07silbGzlLYV66sWgL2CMqLkPiSaO5hm4LKPjKlyn9fxh/Tsr6bFAkWDu1zeVSnbj7qJWGTbLIIo2O2iLzTaoPuPyPGgG8BzY0rL6iHeBjg/pRmKbFz9jRFLg7uLyzQR7+i5XP5/segDON0S46v5EmdJk2oUkNM415MwOUO+c/OTrALvBuva5KKJObA/9dxhBvGoAj/jXBRwa0e2BlX2CM75k1kXH5w=
  app: sweater-weather-django
  on: deploy
  run: python manage.py migrate
