language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
services:
- postgresql
script:
- "./manage.py test"
deploy:
  provider: heroku
  api_key:
    secure: TXYnSVaP/vc8NbXOgeP4hbM3Qkc4HQeOk0AgjHYjKeaXWXbdjNArrGH8yjOcIJb/wreV4GpTQ6+p2u3yVlP06joupQ6IJSZkjvpNb70WDNxHlZ145rkhHLKWTT3ho5QgwPfjHtBZL+iHYbGsXrOLeD2jA63G/DOnTcF72setuPs0Aqh79whvk1TjHtCw6H1kb5hc+HkmmRfaCFp1rjlVqIHlNdMnDO6nyJW2mBGwNajIE5sgsXh9RSY6bSmW29rlUUCKLRWs/k1F0CGIXmq7xHcTn3xRjtrpfTYc1Trj0YfWNtnRtx/USH8znMiVp+30NiKbW+dNV6z2y0cdDTfFfUjKOK/5g86uUQk8xfagx+8vau4KT0FVE8yLlxhbH6uvPKngxl3FOb4U/GW1Z3TMp2fypGwCG8ynC+NdujYtwOoPhrRiyRrxBLnouSNPh57thUfScjfFf9LegxA+5gWxnBjdZNxJz+H5r/cM4nxwoQIexcqN/tazPlvUUcS/HsgXLqyaGiTVp3gIPGCERD1GWqQXI5I3Cju9wOAVkvUiMgGL0mjCPM+QtAU0U6uRc25nuVYpF3mHXoUmVtFXuQfK9wPMDOv9Azh0ff/TV0OMM4fPpdQXbt442su3BlBJ1/GGxPCADebyBZEu6upKc77HrqBYH23aq5mRINAI+UALSkY=
  app: sweater-weather-django
  on: deploy
  run: python manage.py migrate
