# Generated by Django 3.1.2 on 2020-10-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
